@extends('layouts.admin')

@section('title', 'Job Applications | AINCHORS Admin')

@section('content')
    <div class="mb-8">
        <p class="text-xs font-bold uppercase tracking-[0.16em] text-ainchors-green">Recruitment</p>
        <h1 class="mt-2 font-heading text-3xl font-bold text-ainchors-navy sm:text-4xl">Job applications</h1>
        <p class="mt-2 max-w-3xl text-sm leading-relaxed text-ainchors-grey-dark">Review candidates by position and progress. Resumes remain in protected storage and are available only to authorised administrators.</p>
    </div>

    <form method="GET" action="{{ route('admin.job-applications.index') }}" class="mb-6 grid gap-3 rounded-ainchors-card border border-ainchors-navy/10 bg-white p-4 shadow-sm md:grid-cols-[minmax(0,1fr)_12rem_14rem_auto] md:items-end">
        <div><label for="applications-search" class="block text-sm font-semibold text-ainchors-navy">Search</label><input id="applications-search" name="q" type="search" value="{{ request('q') }}" placeholder="Name, email or role" class="mt-2 block w-full rounded-ainchors-button border border-ainchors-grey-light/45 px-3.5 py-2.5 text-sm outline-none transition focus:border-ainchors-green focus:ring-2 focus:ring-ainchors-green/25"></div>
        <div><label for="applications-status" class="block text-sm font-semibold text-ainchors-navy">Status</label><select id="applications-status" name="status" class="mt-2 block w-full rounded-ainchors-button border border-ainchors-grey-light/45 bg-white px-3.5 py-2.5 text-sm"><option value="">All statuses</option>@foreach (['new', 'reviewing', 'shortlisted', 'rejected'] as $status)<option value="{{ $status }}" @selected(request('status') === $status)>{{ str($status)->headline() }}</option>@endforeach</select></div>
        <div><label for="applications-position" class="block text-sm font-semibold text-ainchors-navy">Job position</label><select id="applications-position" name="position_id" class="mt-2 block w-full rounded-ainchors-button border border-ainchors-grey-light/45 bg-white px-3.5 py-2.5 text-sm"><option value="">All positions</option>@foreach ($positions as $position)<option value="{{ $position->id }}" @selected((string) request('position_id') === (string) $position->id)>{{ $position->title }}</option>@endforeach</select></div>
        <div class="flex gap-2"><button type="submit" class="rounded-ainchors-button bg-ainchors-navy px-4 py-2.5 text-sm font-semibold text-white transition hover:bg-ainchors-green">Filter</button><a href="{{ route('admin.job-applications.index') }}" class="rounded-ainchors-button border border-ainchors-navy/15 px-4 py-2.5 text-sm font-semibold text-ainchors-grey-dark hover:border-ainchors-green hover:text-ainchors-green">Reset</a></div>
    </form>

    <section class="overflow-hidden rounded-ainchors-card border border-ainchors-navy/10 bg-white shadow-sm">
        <div class="overflow-x-auto"><table class="w-full min-w-[64rem] text-left text-sm"><caption class="sr-only">AINCHORS job applications</caption><thead class="border-b border-ainchors-navy/10 bg-slate-50 text-xs uppercase tracking-wide text-ainchors-grey-dark"><tr><th scope="col" class="px-5 py-3.5 font-bold">Applicant</th><th scope="col" class="px-5 py-3.5 font-bold">Position</th><th scope="col" class="px-5 py-3.5 font-bold">Availability</th><th scope="col" class="px-5 py-3.5 font-bold">Received</th><th scope="col" class="px-5 py-3.5 font-bold">Status</th><th scope="col" class="px-5 py-3.5 text-right font-bold">Action</th></tr></thead><tbody class="divide-y divide-ainchors-navy/8">@forelse ($applications as $application)<tr><td class="px-5 py-4"><p class="font-semibold text-ainchors-navy">{{ $application->full_name }}</p><p class="mt-1 text-xs text-ainchors-grey-dark">{{ $application->email }}</p></td><td class="px-5 py-4 text-ainchors-grey-dark">{{ $application->jobPosition?->title ?? '—' }}</td><td class="px-5 py-4 text-ainchors-grey-dark">{{ $application->interview_available_on?->format('j M Y') ?? '—' }}</td><td class="px-5 py-4 text-ainchors-grey-dark">{{ $application->created_at?->format('j M Y, H:i') ?? '—' }}</td><td class="px-5 py-4">@include('admin.partials.status-badge', ['status' => $application->status])</td><td class="px-5 py-4 text-right"><a href="{{ route('admin.job-applications.show', $application) }}" class="font-semibold text-ainchors-green hover:text-ainchors-navy">Review<span class="sr-only"> {{ $application->full_name }}</span></a></td></tr>@empty<tr><td colspan="6" class="px-5 py-12 text-center"><p class="font-semibold text-ainchors-navy">No job applications match these filters.</p></td></tr>@endforelse</tbody></table></div>
    </section>
    <div class="mt-6">{{ $applications->onEachSide(1)->links() }}</div>
@endsection
