@extends('layouts.admin')

@section('title', $jobApplication->full_name.' | Job Application | AINCHORS Admin')

@section('content')
    <div class="mx-auto max-w-5xl">
        <a href="{{ route('admin.job-applications.index') }}" class="inline-flex items-center gap-2 text-sm font-semibold text-ainchors-green hover:text-ainchors-navy"><svg class="h-4 w-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" aria-hidden="true"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m15 19-7-7 7-7"/></svg>All job applications</a>
        <div class="mt-5 rounded-ainchors-card border border-ainchors-navy/10 bg-white p-6 shadow-sm sm:p-8">
            <div class="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><p class="text-xs font-bold uppercase tracking-[0.16em] text-ainchors-green">Recruitment · {{ $jobApplication->jobPosition?->title ?? 'Position unavailable' }}</p><h1 class="mt-2 font-heading text-3xl font-bold text-ainchors-navy">{{ $jobApplication->full_name }}</h1><p class="mt-2 text-sm text-ainchors-grey-dark">Received {{ $jobApplication->created_at?->format('j M Y, H:i') ?? '—' }}</p></div>@include('admin.partials.status-badge', ['status' => $jobApplication->status])</div>
            <div class="mt-7 grid gap-6 lg:grid-cols-2"><section><h2 class="font-heading text-2xl font-bold text-ainchors-navy">Applicant details</h2><dl class="mt-4 divide-y divide-ainchors-navy/8 text-sm"><div class="flex justify-between gap-5 py-3"><dt class="font-semibold text-ainchors-grey-dark">Email</dt><dd class="max-w-[15rem] break-words text-right text-ainchors-navy">{{ $jobApplication->email }}</dd></div><div class="flex justify-between gap-5 py-3"><dt class="font-semibold text-ainchors-grey-dark">Phone</dt><dd class="text-right text-ainchors-navy">{{ $jobApplication->phone }}</dd></div><div class="flex justify-between gap-5 py-3"><dt class="font-semibold text-ainchors-grey-dark">Interview availability</dt><dd class="text-right text-ainchors-navy">{{ $jobApplication->interview_available_on?->format('j M Y') ?? 'Not provided' }}</dd></div></dl><a href="{{ route('admin.job-applications.resume', $jobApplication) }}" class="mt-5 inline-flex rounded-ainchors-button bg-ainchors-navy px-4 py-2.5 text-sm font-semibold text-white transition hover:bg-ainchors-green">Download resume</a><p class="mt-2 text-xs text-ainchors-grey-dark">The protected file path is not displayed or publicly accessible.</p></section><section class="rounded-ainchors-button bg-slate-50 p-5"><h2 class="font-heading text-xl font-bold text-ainchors-navy">Review application</h2><form method="POST" action="{{ route('admin.job-applications.update', $jobApplication) }}" class="mt-5 space-y-4">@csrf @method('PUT')<div><label for="application-status" class="block text-sm font-semibold text-ainchors-navy">Status</label><select id="application-status" name="status" class="mt-2 block w-full rounded-ainchors-button border border-ainchors-grey-light/45 bg-white px-3.5 py-2.5 text-sm">@foreach (['new', 'reviewing', 'shortlisted', 'rejected'] as $status)<option value="{{ $status }}" @selected($jobApplication->status === $status)>{{ str($status)->headline() }}</option>@endforeach</select></div><div><label for="internal-notes" class="block text-sm font-semibold text-ainchors-navy">Internal notes</label><textarea id="internal-notes" name="internal_notes" rows="5" class="mt-2 block w-full rounded-ainchors-button border border-ainchors-grey-light/45 bg-white px-3.5 py-2.5 text-sm" placeholder="Visible to authorised administrators only">{{ old('internal_notes', $jobApplication->internal_notes) }}</textarea></div><button type="submit" class="rounded-ainchors-button bg-ainchors-green px-4 py-2.5 text-sm font-semibold text-white transition hover:bg-ainchors-navy">Save review</button></form></section></div>
            @if (filled($jobApplication->short_note))<section class="mt-7 border-t border-ainchors-navy/10 pt-6"><h2 class="font-heading text-2xl font-bold text-ainchors-navy">Candidate note</h2><p class="mt-3 whitespace-pre-line text-sm leading-relaxed text-ainchors-grey-dark">{{ $jobApplication->short_note }}</p></section>@endif
            <section class="mt-7 border-t border-ainchors-navy/10 pt-6"><h2 class="font-heading text-2xl font-bold text-ainchors-navy">Status history</h2><ol class="mt-4 space-y-3">@forelse ($jobApplication->statusHistory as $history)<li class="rounded-ainchors-button border border-ainchors-navy/10 px-4 py-3 text-sm"><span class="font-semibold text-ainchors-navy">{{ str($history->status)->headline() }}</span><span class="text-ainchors-grey-dark"> · {{ $history->changedBy?->full_name ?? 'System' }} · {{ $history->created_at?->format('j M Y, H:i') ?? '—' }}</span></li>@empty<li class="text-sm text-ainchors-grey-dark">No status history is available.</li>@endforelse</ol></section>
        </div>
    </div>
@endsection
