@extends('layouts.admin')

@section('title', 'Payments | AINCHORS Admin')

@section('content')
    <div class="mb-8"><p class="text-xs font-bold uppercase tracking-[0.16em] text-ainchors-green">Commerce records</p><h1 class="mt-2 font-heading text-3xl font-bold text-ainchors-navy sm:text-4xl">Payments</h1><p class="mt-2 max-w-3xl text-sm leading-relaxed text-ainchors-grey-dark">Payment data is available for inspection only. Provider data, card details and transaction secrets are never exposed here.</p></div>
    <form method="GET" action="{{ route('admin.payments.index') }}" class="mb-6 grid gap-3 rounded-ainchors-card border border-ainchors-navy/10 bg-white p-4 shadow-sm sm:grid-cols-[minmax(0,1fr)_10rem_10rem_auto] sm:items-end"><div><label for="payments-search" class="block text-sm font-semibold text-ainchors-navy">Search</label><input id="payments-search" name="q" type="search" value="{{ request('q') }}" placeholder="Order, customer or provider" class="mt-2 block w-full rounded-ainchors-button border border-ainchors-grey-light/45 px-3.5 py-2.5 text-sm outline-none transition focus:border-ainchors-green focus:ring-2 focus:ring-ainchors-green/25"></div><div><label for="payments-status" class="block text-sm font-semibold text-ainchors-navy">Status</label><select id="payments-status" name="status" class="mt-2 block w-full rounded-ainchors-button border border-ainchors-grey-light/45 bg-white px-3.5 py-2.5 text-sm outline-none transition focus:border-ainchors-green focus:ring-2 focus:ring-ainchors-green/25"><option value="">All statuses</option>@foreach (['pending', 'processing', 'paid', 'failed', 'refunded'] as $status)<option value="{{ $status }}" @selected(request('status') === $status)>{{ str($status)->headline() }}</option>@endforeach</select></div><div><label for="payments-provider" class="block text-sm font-semibold text-ainchors-navy">Provider</label><input id="payments-provider" name="provider" type="text" value="{{ request('provider') }}" placeholder="Any provider" class="mt-2 block w-full rounded-ainchors-button border border-ainchors-grey-light/45 px-3.5 py-2.5 text-sm outline-none transition focus:border-ainchors-green focus:ring-2 focus:ring-ainchors-green/25"></div><div class="flex gap-2"><button type="submit" class="rounded-ainchors-button bg-ainchors-navy px-4 py-2.5 text-sm font-semibold text-white transition hover:bg-ainchors-green focus:outline-none focus:ring-2 focus:ring-ainchors-green focus:ring-offset-2">Filter</button><a href="{{ route('admin.payments.index') }}" class="rounded-ainchors-button border border-ainchors-navy/15 px-4 py-2.5 text-sm font-semibold text-ainchors-grey-dark transition hover:border-ainchors-green hover:text-ainchors-green focus:outline-none focus:ring-2 focus:ring-ainchors-green">Reset</a></div></form>
    <section aria-labelledby="payments-table-heading" class="overflow-hidden rounded-ainchors-card border border-ainchors-navy/10 bg-white shadow-sm"><h2 id="payments-table-heading" class="sr-only">Payment records</h2><div class="overflow-x-auto"><table class="w-full min-w-[54rem] text-left text-sm"><caption class="sr-only">AINCHORS payment records</caption><thead class="border-b border-ainchors-navy/10 bg-slate-50 text-xs uppercase tracking-wide text-ainchors-grey-dark"><tr><th scope="col" class="px-5 py-3.5 font-bold">Order</th><th scope="col" class="px-5 py-3.5 font-bold">Provider</th><th scope="col" class="px-5 py-3.5 font-bold">Status</th><th scope="col" class="px-5 py-3.5 font-bold">Paid at</th><th scope="col" class="px-5 py-3.5 text-right font-bold">Amount</th><th scope="col" class="px-5 py-3.5 text-right font-bold">Action</th></tr></thead><tbody class="divide-y divide-ainchors-navy/8">@forelse ($payments as $payment)<tr><td class="px-5 py-4 font-semibold text-ainchors-navy">{{ $payment->order?->order_number ?? 'Order unavailable' }}</td><td class="px-5 py-4 text-ainchors-grey-dark">{{ strtolower($payment->provider) === 'demo' ? 'Demo/test payment' : $payment->provider }}</td><td class="px-5 py-4">@include('admin.partials.status-badge', ['status' => $payment->status])</td><td class="px-5 py-4 text-ainchors-grey-dark">{{ $payment->paid_at?->format('j M Y, H:i') ?? '—' }}</td><td class="px-5 py-4 text-right font-semibold text-ainchors-navy">{{ $payment->currency }} {{ number_format((float) $payment->amount, 2) }}</td><td class="px-5 py-4 text-right"><a href="{{ route('admin.payments.show', $payment) }}" class="font-semibold text-ainchors-green hover:text-ainchors-navy focus:outline-none focus:ring-2 focus:ring-ainchors-green">Inspect</a></td></tr>@empty<tr><td colspan="6" class="px-5 py-12 text-center"><p class="font-semibold text-ainchors-navy">No payments match these filters.</p><p class="mt-1 text-sm text-ainchors-grey-dark">Payment records appear when a checkout is processed.</p></td></tr>@endforelse</tbody></table></div></section>
    @if (method_exists($payments, 'links'))<div class="mt-6">{{ $payments->onEachSide(1)->links() }}</div>@endif
@endsection
