<?php

return [
    'settings' => [
        'welcome_modal_frequency' => 'every_page',
    ],
    'navigation' => [
        ['label' => 'Home', 'url' => '/home'],
        ['label' => 'About us', 'url' => '/about-us'],
        [
            'label' => 'Training',
            'url' => '/trainers-profile',
            'children' => [
                ['label' => 'Trainer Profiles', 'url' => '/trainers-profile'],
                ['label' => 'Testimonials', 'url' => '/testimonials'],
                ['label' => 'Courses', 'url' => '/courses'],
                ['label' => 'Success Story', 'url' => '/success-story-of-angie'],
            ],
        ],
        [
            'label' => 'Consulting',
            'url' => '/consulting-main',
            'children' => [
                ['label' => 'Public/Government Sector', 'url' => '/consulting-gov'],
                ['label' => 'Private Sector', 'url' => '/consulting-private'],
            ],
        ],
        ['label' => 'FAQ’s', 'url' => '/faqs'],
        ['label' => 'Join Us', 'url' => '/hiring-page'],
        ['label' => 'Contact us', 'url' => '/contact-us', 'featured' => true],
    ],
    'clients' => [
        ['image' => 'assets/partners/cpa-australia.png', 'alt' => 'CPA Australia'],
        ['image' => 'assets/partners/citi.png', 'alt' => 'Citi'],
        ['image' => 'assets/partners/orbis-business-school.png', 'alt' => 'Orbis Business School'],
        ['image' => 'assets/partners/gientech.png', 'alt' => 'GienTech'],
        ['image' => 'assets/partners/banque-saudi-fransi.png', 'alt' => 'Banque Saudi Fransi'],
        ['image' => 'assets/partners/neueda.png', 'alt' => 'Neueda'],
        ['image' => 'assets/partners/ipg-media-brands.png', 'alt' => 'IPG Media Brands'],
        ['image' => 'assets/partners/dialectica.png', 'alt' => 'Dialectica'],
        ['image' => 'assets/partners/fitch-learning.jpeg', 'alt' => 'Fitch Learning'],
        ['image' => 'assets/partners/commercial-bank-of-dubai.jpeg', 'alt' => 'Commercial Bank of Dubai'],
        ['image' => 'assets/partners/saudi-central-bank.png', 'alt' => 'Saudi Central Bank'],
        ['image' => 'assets/partners/ksk-land.png', 'alt' => 'KSK Land'],
        ['image' => 'assets/partners/penny-idea.jpg', 'alt' => 'Penny Idea'],
        ['image' => 'assets/partners/emirates-institute-of-finance.png', 'alt' => 'Emirates Institute of Finance'],
        ['image' => 'assets/partners/fonco.jpeg', 'alt' => 'FONCO'],
    ],
    'footer' => [
        'australia' => [
            'AI Anchor Solutions Pty Ltd',
            'ACN No: 691339714',
            'ABN No: 99691339714',
            'Address: U803 5 Waterways Street Wentworth Point NSW 2127 Australia',
        ],
        'malaysia' => [
            'AINCHORS Sdn Bhd',
            '(Formerly registered as Anchors Solution Sdn Bhd)',
            '202001021528 (1377848K)',
            'Tel: +60167022788',
            'Address: Level 13A, Wisma Mont Kiara, 1, Jalan Kiara, Mont Kiara, 50480 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur',
        ],
    ],
    'legacy_paths' => [
        'about-us',
        'ai-prompt-engineering101-course',
        'ai-prompt-engineering101-course-',
        'blogs',
        'boooking-page',
        'cart',
        'cbdccheckoutpage',
        'check-out-page-page',
        'check-out-page2',
        'check-out-pagecourse-00',
        'check-out-pagecourse-individual',
        'check-out-pagecourse-individualaiprompt',
        'check-out-pagecourse-individualdataanalytics',
        'check-out-pagecourse-individualdigital',
        'check-out-pagecourse23',
        'check-out-pagecoursedeale',
        'check-out-pagecoursefintech',
        'check-out-pageepayment',
        'check-out-pagefinancial',
        'checkout',
        'checkout-page-684967',
        'checkout-page-physicalcourse-6610',
        'checkout-page-onlinecourse',
        'checkout-page123',
        'checkout-page6767',
        'checkoutfintech',
        'consulting-gov',
        'consulting-main',
        'consulting-private',
        'contact-us',
        'courses',
        'digitalmarketing',
        'events',
        'faqs',
        'financialliteracymastery',
        'fondy-foong',
        'hiring-page',
        'individual-aiprompt',
        'individualcbdc',
        'individualepayment',
        'individualfintech',
        'join-our-campaign',
        'package-page',
        'package-page-12',
        'package-page-4066',
        'package-page-4157',
        'package-page-6219',
        'package-page-6341',
        'package-page-9865',
        'package-page-dataanalytics',
        'package-page-page-303665',
        'package-pagefi',
        'physical-course',
        'privacy--policy',
        'products-list',
        'single-course',
        'single-even',
        'success-story-of-angie',
        'terms--conditions',
        'testimonials',
        'thank-you-7357',
        'trainers-profile',
        'training',
    ],
];
