@extends('layouts.admin')

@section('title', 'Orders | AINCHORS Admin')

@section('content')
    <div class="mb-8"><p class="text-xs font-bold uppercase tracking-[0.16em] text-ainchors-green">Commerce records</p><h1 class="mt-2 font-heading text-3xl font-bold text-ainchors-navy sm:text-4xl">Orders</h1><p class="mt-2 max-w-3xl text-sm leading-relaxed text-ainchors-grey-dark">Historical order records are read-only to protect auditability of completed transactions.</p></div>

    <form method="GET" action="{{ route('admin.orders.index') }}" class="mb-6 grid gap-3 rounded-ainchors-card border border-ainchors-navy/10 bg-white p-4 shadow-sm sm:grid-cols-[minmax(0,1fr)_11rem_auto] sm:items-end"><div><label for="orders-search" class="block text-sm font-semibold text-ainchors-navy">Search</label><input id="orders-search" name="q" type="search" value="{{ request('q') }}" placeholder="Order number, customer or email" class="mt-2 block w-full rounded-ainchors-button border border-ainchors-grey-light/45 px-3.5 py-2.5 text-sm outline-none transition focus:border-ainchors-green focus:ring-2 focus:ring-ainchors-green/25"></div><div><label for="orders-status" class="block text-sm font-semibold text-ainchors-navy">Status</label><select id="orders-status" name="status" class="mt-2 block w-full rounded-ainchors-button border border-ainchors-grey-light/45 bg-white px-3.5 py-2.5 text-sm outline-none transition focus:border-ainchors-green focus:ring-2 focus:ring-ainchors-green/25"><option value="">All statuses</option>@foreach (['pending', 'awaiting_payment', 'paid', 'completed', 'cancelled', 'refunded'] as $status)<option value="{{ $status }}" @selected(request('status') === $status)>{{ str($status)->replace('_', ' ')->headline() }}</option>@endforeach</select></div><div class="flex gap-2"><button type="submit" class="rounded-ainchors-button bg-ainchors-navy px-4 py-2.5 text-sm font-semibold text-white transition hover:bg-ainchors-green focus:outline-none focus:ring-2 focus:ring-ainchors-green focus:ring-offset-2">Filter</button><a href="{{ route('admin.orders.index') }}" class="rounded-ainchors-button border border-ainchors-navy/15 px-4 py-2.5 text-sm font-semibold text-ainchors-grey-dark transition hover:border-ainchors-green hover:text-ainchors-green focus:outline-none focus:ring-2 focus:ring-ainchors-green">Reset</a></div></form>

    <section aria-labelledby="orders-table-heading" class="overflow-hidden rounded-ainchors-card border border-ainchors-navy/10 bg-white shadow-sm"><h2 id="orders-table-heading" class="sr-only">Order records</h2><div class="overflow-x-auto"><table class="w-full min-w-[55rem] text-left text-sm"><caption class="sr-only">AINCHORS order records</caption><thead class="border-b border-ainchors-navy/10 bg-slate-50 text-xs uppercase tracking-wide text-ainchors-grey-dark"><tr><th scope="col" class="px-5 py-3.5 font-bold">Order</th><th scope="col" class="px-5 py-3.5 font-bold">Customer</th><th scope="col" class="px-5 py-3.5 font-bold">Status</th><th scope="col" class="px-5 py-3.5 font-bold">Placed</th><th scope="col" class="px-5 py-3.5 text-right font-bold">Total</th><th scope="col" class="px-5 py-3.5 text-right font-bold">Action</th></tr></thead><tbody class="divide-y divide-ainchors-navy/8">@forelse ($orders as $order)<tr><td class="px-5 py-4 font-semibold text-ainchors-navy">{{ $order->order_number }}</td><td class="px-5 py-4"><p class="text-ainchors-navy">{{ $order->user?->full_name ?? 'Customer unavailable' }}</p><p class="mt-1 text-xs text-ainchors-grey-dark">{{ $order->user?->email ?? '—' }}</p></td><td class="px-5 py-4">@include('admin.partials.status-badge', ['status' => $order->status])</td><td class="px-5 py-4 text-ainchors-grey-dark">{{ $order->placed_at?->format('j M Y, H:i') ?? 'Not placed' }}</td><td class="px-5 py-4 text-right font-semibold text-ainchors-navy">{{ $order->currency }} {{ number_format((float) $order->total_amount, 2) }}</td><td class="px-5 py-4 text-right"><a href="{{ route('admin.orders.show', $order) }}" class="font-semibold text-ainchors-green hover:text-ainchors-navy focus:outline-none focus:ring-2 focus:ring-ainchors-green">Inspect<span class="sr-only"> {{ $order->order_number }}</span></a></td></tr>@empty<tr><td colspan="6" class="px-5 py-12 text-center"><p class="font-semibold text-ainchors-navy">No orders match these filters.</p><p class="mt-1 text-sm text-ainchors-grey-dark">Orders will appear here when customers begin checkout.</p></td></tr>@endforelse</tbody></table></div></section>
    @if (method_exists($orders, 'links'))<div class="mt-6">{{ $orders->onEachSide(1)->links() }}</div>@endif
@endsection
