@extends('layouts.admin')

@section('title', 'Edit '.$product->name.' | AINCHORS Admin')

@section('content')
    <div class="mx-auto max-w-4xl"><a href="{{ route('admin.products.show', $product) }}" class="inline-flex items-center gap-2 text-sm font-semibold text-ainchors-green transition hover:text-ainchors-navy focus:outline-none focus:ring-2 focus:ring-ainchors-green"><svg class="h-4 w-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" aria-hidden="true"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m15 19-7-7 7-7"/></svg>Product details</a><div class="mt-5 rounded-ainchors-card border border-ainchors-navy/10 bg-white p-6 shadow-sm sm:p-8"><div class="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><p class="text-xs font-bold uppercase tracking-[0.16em] text-ainchors-green">Catalogue management</p><h1 class="mt-2 font-heading text-3xl font-bold text-ainchors-navy">Edit product</h1><p class="mt-2 text-sm leading-relaxed text-ainchors-grey-dark">Changes to the catalogue do not alter historical order line items.</p></div>@include('admin.partials.status-badge', ['status' => $product->status])</div><form method="POST" action="{{ route('admin.products.update', $product) }}" class="mt-7 space-y-7">@csrf @method('PUT') @include('admin.products.partials.fields', ['product' => $product])<div class="flex flex-wrap justify-end gap-3 border-t border-ainchors-navy/10 pt-6"><a href="{{ route('admin.products.show', $product) }}" class="rounded-ainchors-button border border-ainchors-navy/15 px-4 py-2.5 text-sm font-semibold text-ainchors-grey-dark transition hover:border-ainchors-green hover:text-ainchors-green focus:outline-none focus:ring-2 focus:ring-ainchors-green">Cancel</a><button type="submit" class="rounded-ainchors-button bg-ainchors-green px-4 py-2.5 text-sm font-semibold text-white transition hover:bg-ainchors-navy focus:outline-none focus:ring-2 focus:ring-ainchors-green focus:ring-offset-2">Save changes</button></div></form></div>

        <section aria-labelledby="product-status-heading" class="mt-6 rounded-ainchors-card border border-ainchors-navy/10 bg-white p-6 shadow-sm sm:p-8"><h2 id="product-status-heading" class="font-heading text-2xl font-bold text-ainchors-navy">Catalogue availability</h2><p class="mt-2 text-sm leading-relaxed text-ainchors-grey-dark">Use status changes rather than deletion to retain product references in historical transactions.</p><form method="POST" action="{{ route('admin.products.status', $product) }}" class="mt-5 flex flex-wrap items-center justify-between gap-4 rounded-ainchors-button bg-slate-50 p-4">@csrf @method('PATCH')<div><p class="font-semibold text-ainchors-navy">Current status: @include('admin.partials.status-badge', ['status' => $product->status])</p><p class="mt-1 text-sm text-ainchors-grey-dark">{{ $product->status === 'active' ? 'This product is available in the catalogue.' : 'This product is not available for new purchases.' }}</p></div><label class="sr-only" for="product-update-status">New product status</label><select id="product-update-status" name="status" class="rounded-ainchors-button border border-ainchors-grey-light/45 bg-white px-3 py-2.5 text-sm text-ainchors-navy focus:border-ainchors-green focus:ring-2 focus:ring-ainchors-green/25"><option value="draft" @selected($product->status === 'draft')>Draft</option><option value="active" @selected($product->status === 'active')>Active</option><option value="inactive" @selected($product->status === 'inactive')>Inactive</option></select><button type="submit" class="rounded-ainchors-button border border-ainchors-navy/15 bg-white px-4 py-2.5 text-sm font-semibold text-ainchors-navy transition hover:border-ainchors-green hover:text-ainchors-green focus:outline-none focus:ring-2 focus:ring-ainchors-green">Update status</button></form></section>
    </div>
@endsection
