@extends('layouts.admin')

@section('title', 'Products | AINCHORS Admin')

@section('content')
    <div class="mb-8 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p class="text-xs font-bold uppercase tracking-[0.16em] text-ainchors-green">Catalogue management</p><h1 class="mt-2 font-heading text-3xl font-bold text-ainchors-navy sm:text-4xl">Products</h1><p class="mt-2 text-sm leading-relaxed text-ainchors-grey-dark">Create and maintain catalogue records without deleting products that may be referenced by historical orders.</p></div><a href="{{ route('admin.products.create') }}" class="inline-flex items-center justify-center rounded-ainchors-button bg-ainchors-green px-4 py-2.5 text-sm font-semibold text-white transition hover:bg-ainchors-navy focus:outline-none focus:ring-2 focus:ring-ainchors-green focus:ring-offset-2">Add product</a></div>

    <form method="GET" action="{{ route('admin.products.index') }}" class="mb-6 grid gap-3 rounded-ainchors-card border border-ainchors-navy/10 bg-white p-4 shadow-sm sm:grid-cols-[minmax(0,1fr)_11rem_10rem_auto] sm:items-end"><div><label for="products-search" class="block text-sm font-semibold text-ainchors-navy">Search</label><input id="products-search" name="q" type="search" value="{{ request('q') }}" placeholder="Name, SKU or slug" class="mt-2 block w-full rounded-ainchors-button border border-ainchors-grey-light/45 px-3.5 py-2.5 text-sm outline-none transition focus:border-ainchors-green focus:ring-2 focus:ring-ainchors-green/25"></div><div><label for="products-type" class="block text-sm font-semibold text-ainchors-navy">Type</label><select id="products-type" name="type" class="mt-2 block w-full rounded-ainchors-button border border-ainchors-grey-light/45 bg-white px-3.5 py-2.5 text-sm outline-none transition focus:border-ainchors-green focus:ring-2 focus:ring-ainchors-green/25"><option value="">All types</option><option value="course" @selected(request('type') === 'course')>Course</option><option value="course_package" @selected(request('type') === 'course_package')>Course package</option><option value="consulting" @selected(request('type') === 'consulting')>Consulting</option><option value="service" @selected(request('type') === 'service')>Service</option></select></div><div><label for="products-status" class="block text-sm font-semibold text-ainchors-navy">Status</label><select id="products-status" name="status" class="mt-2 block w-full rounded-ainchors-button border border-ainchors-grey-light/45 bg-white px-3.5 py-2.5 text-sm outline-none transition focus:border-ainchors-green focus:ring-2 focus:ring-ainchors-green/25"><option value="">All statuses</option><option value="draft" @selected(request('status') === 'draft')>Draft</option><option value="active" @selected(request('status') === 'active')>Active</option><option value="inactive" @selected(request('status') === 'inactive')>Inactive</option></select></div><div class="flex gap-2"><button type="submit" class="rounded-ainchors-button bg-ainchors-navy px-4 py-2.5 text-sm font-semibold text-white transition hover:bg-ainchors-green focus:outline-none focus:ring-2 focus:ring-ainchors-green focus:ring-offset-2">Filter</button><a href="{{ route('admin.products.index') }}" class="rounded-ainchors-button border border-ainchors-navy/15 px-4 py-2.5 text-sm font-semibold text-ainchors-grey-dark transition hover:border-ainchors-green hover:text-ainchors-green focus:outline-none focus:ring-2 focus:ring-ainchors-green">Reset</a></div></form>

    <section aria-labelledby="products-table-heading" class="overflow-hidden rounded-ainchors-card border border-ainchors-navy/10 bg-white shadow-sm"><h2 id="products-table-heading" class="sr-only">Product catalogue</h2><div class="overflow-x-auto"><table class="w-full min-w-[54rem] text-left text-sm"><caption class="sr-only">AINCHORS product catalogue</caption><thead class="border-b border-ainchors-navy/10 bg-slate-50 text-xs uppercase tracking-wide text-ainchors-grey-dark"><tr><th scope="col" class="px-5 py-3.5 font-bold">Product</th><th scope="col" class="px-5 py-3.5 font-bold">Type</th><th scope="col" class="px-5 py-3.5 font-bold">Price</th><th scope="col" class="px-5 py-3.5 font-bold">Status</th><th scope="col" class="px-5 py-3.5 font-bold">Updated</th><th scope="col" class="px-5 py-3.5 text-right font-bold">Actions</th></tr></thead><tbody class="divide-y divide-ainchors-navy/8">@forelse ($products as $product)<tr><td class="px-5 py-4"><p class="font-semibold text-ainchors-navy">{{ $product->name }}</p><p class="mt-1 text-xs text-ainchors-grey-dark">{{ $product->sku }}</p></td><td class="px-5 py-4 text-ainchors-grey-dark">{{ str($product->type)->replace('_', ' ')->headline() }}</td><td class="px-5 py-4 font-semibold text-ainchors-navy">{{ $product->price === null ? 'Custom' : $product->currency.' '.number_format((float) $product->price, 2) }}</td><td class="px-5 py-4">@include('admin.partials.status-badge', ['status' => $product->status])</td><td class="px-5 py-4 text-ainchors-grey-dark">{{ $product->updated_at?->format('j M Y') ?? '—' }}</td><td class="px-5 py-4"><div class="flex justify-end gap-4"><a href="{{ route('admin.products.show', $product) }}" class="font-semibold text-ainchors-green hover:text-ainchors-navy focus:outline-none focus:ring-2 focus:ring-ainchors-green">View<span class="sr-only"> {{ $product->name }}</span></a><a href="{{ route('admin.products.edit', $product) }}" class="font-semibold text-ainchors-green hover:text-ainchors-navy focus:outline-none focus:ring-2 focus:ring-ainchors-green">Edit<span class="sr-only"> {{ $product->name }}</span></a></div></td></tr>@empty<tr><td colspan="6" class="px-5 py-12 text-center"><p class="font-semibold text-ainchors-navy">No products match these filters.</p><p class="mt-1 text-sm text-ainchors-grey-dark">Create a product to start building the catalogue.</p></td></tr>@endforelse</tbody></table></div></section>
    @if (method_exists($products, 'links'))<div class="mt-6">{{ $products->onEachSide(1)->links() }}</div>@endif
@endsection
