@extends('layouts.admin')

@section('title', $product->name.' | AINCHORS Admin')

@section('content')
    <div class="mb-8 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><a href="{{ route('admin.products.index') }}" class="inline-flex items-center gap-2 text-sm font-semibold text-ainchors-green transition hover:text-ainchors-navy focus:outline-none focus:ring-2 focus:ring-ainchors-green"><svg class="h-4 w-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" aria-hidden="true"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m15 19-7-7 7-7"/></svg>All products</a><div class="mt-4 flex flex-wrap items-center gap-3"><h1 class="font-heading text-3xl font-bold text-ainchors-navy sm:text-4xl">{{ $product->name }}</h1>@include('admin.partials.status-badge', ['status' => $product->status])</div><p class="mt-2 text-sm text-ainchors-grey-dark">{{ $product->sku }} · {{ str($product->type)->replace('_', ' ')->headline() }}</p></div><a href="{{ route('admin.products.edit', $product) }}" class="inline-flex items-center justify-center rounded-ainchors-button bg-ainchors-green px-4 py-2.5 text-sm font-semibold text-white transition hover:bg-ainchors-navy focus:outline-none focus:ring-2 focus:ring-ainchors-green focus:ring-offset-2">Edit product</a></div>

    <div class="grid gap-6 xl:grid-cols-[minmax(0,1.35fr)_minmax(18rem,0.65fr)]"><section aria-labelledby="product-description-heading" class="rounded-ainchors-card border border-ainchors-navy/10 bg-white p-6 shadow-sm"><h2 id="product-description-heading" class="font-heading text-2xl font-bold text-ainchors-navy">Catalogue copy</h2><p class="mt-5 whitespace-pre-line text-sm leading-relaxed text-ainchors-grey-dark">{{ $product->description ?: ($product->short_description ?: 'No catalogue description has been added.') }}</p></section><section aria-labelledby="product-details-heading" class="rounded-ainchors-card border border-ainchors-navy/10 bg-white p-6 shadow-sm"><h2 id="product-details-heading" class="font-heading text-2xl font-bold text-ainchors-navy">Product details</h2><dl class="mt-5 divide-y divide-ainchors-navy/8 text-sm"><div class="flex justify-between gap-5 py-3"><dt class="font-semibold text-ainchors-grey-dark">Price</dt><dd class="text-right font-semibold text-ainchors-navy">{{ $product->price === null ? 'Custom' : $product->currency.' '.number_format((float) $product->price, 2) }}</dd></div><div class="flex justify-between gap-5 py-3"><dt class="font-semibold text-ainchors-grey-dark">Billing</dt><dd class="text-right text-ainchors-navy">{{ str($product->billing_type)->replace('_', ' ')->headline() }}</dd></div><div class="flex justify-between gap-5 py-3"><dt class="font-semibold text-ainchors-grey-dark">Slug</dt><dd class="max-w-[13rem] break-words text-right text-ainchors-navy">{{ $product->slug }}</dd></div><div class="flex justify-between gap-5 py-3"><dt class="font-semibold text-ainchors-grey-dark">Last updated</dt><dd class="text-right text-ainchors-navy">{{ $product->updated_at?->format('j M Y, H:i') ?? '—' }}</dd></div></dl></section></div>

    @if ($product->type === 'course')
        <section aria-labelledby="course-content-heading" class="mt-6 rounded-ainchors-card border border-ainchors-navy/10 bg-white p-6 shadow-sm"><div class="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 id="course-content-heading" class="font-heading text-2xl font-bold text-ainchors-navy">Course content metadata</h2><p class="mt-1 text-sm leading-relaxed text-ainchors-grey-dark">Manage descriptive metadata without exposing protected media locations.</p></div>@if ($product->courseContent)<a href="{{ route('admin.course-content.edit', $product->courseContent) }}" class="inline-flex justify-center rounded-ainchors-button border border-ainchors-green px-4 py-2.5 text-sm font-semibold text-ainchors-green transition hover:bg-ainchors-green hover:text-white focus:outline-none focus:ring-2 focus:ring-ainchors-green">Edit course content</a>@else<a href="{{ route('admin.course-content.create', ['product_id' => $product->id]) }}" class="inline-flex justify-center rounded-ainchors-button border border-ainchors-green px-4 py-2.5 text-sm font-semibold text-ainchors-green transition hover:bg-ainchors-green hover:text-white focus:outline-none focus:ring-2 focus:ring-ainchors-green">Add course content</a>@endif</div></section>
    @endif
@endsection
