@extends('layouts.admin')

@section('title', 'Course Content | AINCHORS Admin')

@section('content')
    <div class="mb-8"><p class="text-xs font-bold uppercase tracking-[0.16em] text-ainchors-green">Learning management</p><h1 class="mt-2 font-heading text-3xl font-bold text-ainchors-navy sm:text-4xl">Course content</h1><p class="mt-2 max-w-3xl text-sm leading-relaxed text-ainchors-grey-dark">Manage safe display metadata for AINCHORS course content. Private streaming and download locations are deliberately never shown.</p></div>

    <section aria-labelledby="course-content-table-heading" class="overflow-hidden rounded-ainchors-card border border-ainchors-navy/10 bg-white shadow-sm"><h2 id="course-content-table-heading" class="sr-only">Course content metadata</h2><div class="overflow-x-auto"><table class="w-full min-w-[52rem] text-left text-sm"><caption class="sr-only">Courses and their managed content metadata</caption><thead class="border-b border-ainchors-navy/10 bg-slate-50 text-xs uppercase tracking-wide text-ainchors-grey-dark"><tr><th scope="col" class="px-5 py-3.5 font-bold">Course</th><th scope="col" class="px-5 py-3.5 font-bold">Video metadata</th><th scope="col" class="px-5 py-3.5 font-bold">Slide metadata</th><th scope="col" class="px-5 py-3.5 text-right font-bold">Action</th></tr></thead><tbody class="divide-y divide-ainchors-navy/8">@forelse ($courses as $course)@php($courseContent = $course->courseContent)<tr><td class="px-5 py-4"><p class="font-semibold text-ainchors-navy">{{ $course->name }}</p><p class="mt-1 text-xs text-ainchors-grey-dark">{{ $course->sku }}</p></td><td class="px-5 py-4 text-ainchors-grey-dark">{{ $courseContent?->video_title ?: 'Not configured' }}@if ($courseContent?->video_provider)<span class="mt-1 block text-xs">{{ $courseContent->video_provider }}</span>@endif</td><td class="px-5 py-4 text-ainchors-grey-dark">{{ $courseContent?->slide_name ?: 'Not configured' }}</td><td class="px-5 py-4 text-right">@if ($courseContent)<a href="{{ route('admin.course-content.edit', $courseContent) }}" class="font-semibold text-ainchors-green hover:text-ainchors-navy focus:outline-none focus:ring-2 focus:ring-ainchors-green">Edit<span class="sr-only"> {{ $course->name }} content</span></a>@else<a href="{{ route('admin.course-content.create', ['product_id' => $course->id]) }}" class="font-semibold text-ainchors-green hover:text-ainchors-navy focus:outline-none focus:ring-2 focus:ring-ainchors-green">Add metadata<span class="sr-only"> for {{ $course->name }}</span></a>@endif</td></tr>@empty<tr><td colspan="4" class="px-5 py-12 text-center"><p class="font-semibold text-ainchors-navy">No course products are available.</p><p class="mt-1 text-sm text-ainchors-grey-dark">Create a course product before adding course content metadata.</p></td></tr>@endforelse</tbody></table></div></section>
    @if (method_exists($courses, 'links'))<div class="mt-6">{{ $courses->onEachSide(1)->links() }}</div>@endif
@endsection
